### ISSUE TITLE
FatalThrowableError In MigrationCreator.php line 156

### ISSUE THREAD

**Issue by kitoki** [laravel-admin-extensions/helpers#18]
- Laravel Version: v5.6.28
- PHP Version: 7.2.3
- Laravel-admin: v1.5.15

### Description:

Model and Controller succeed created, but, there is a warning that appears.
Sorry, i'm new, so, i dont quite understand what it mean.

this is what happen when i sumbit.
helpers -> scaffold :

FatalThrowableError In MigrationCreator.php line 156 : 
- Too few arguments to function Illuminate\Database\Migrations\MigrationCreator::firePostCreateHooks()
- 0 passed in \vendor\laravel-admin-ext\helpers\src\Scaffold\MigrationCreator.php on line 34 and exactly 1 expected

### Steps To Reproduce:
![images-1](https://user-images.githubusercontent.com/20715218/43378683-9fc7f7c6-93f2-11e8-9fd5-05cbd10f439f.png)

**Comment by whw2016** [comment]
hi,i found go to line MigrationCreator.php on line 34, add $table is ok.

**Comment by kitoki** [comment]
hm, hm, i still dont get it.
say what requitment to get error "Too few arguments to function"?

**Comment by z-song** [comment]
Fixed, upgrade laravel-admin-ext/helpers to `v1.1.1`
