### ISSUE TITLE
不支持Laravel6.0，创建时caffold.blade.php line 93出错

### ISSUE THREAD

**Issue by datangkang123** [laravel-admin-extensions/helpers#26]
出错提示：
` ViewException In scaffold.blade.php line 93 :
  Call to undefined function array_get() (View: ../vendor/laravel-admin-ext/helpers/resources/views/scaffold.blade.php)`

此行代码：
`<input type="checkbox" name="fields[{{$index}}][nullable]" {{ array_get($field, 'nullable') == 'on' ? 'checked': '' }}/>`

**Comment by z-song** [comment]
已经提交修复，更新到最新版本
