### ISSUE TITLE
Laravel admin 2 Class 'Encore\Admin\Assets' not found

### ISSUE THREAD

**Issue by caoxl-c** [laravel-admin-extensions/helpers#32]
LaravelAdmin2 ➤ php artisan admin:import helpers

   Error

  Class 'Encore\Admin\Assets' not found

  at vendor/laravel-admin-ext/helpers/src/HelpersServiceProvider.php:19
     15▕         $this->loadViewsFrom(__DIR__.'/../resources/views', 'laravel-admin-helpers');
     16▕
     17▕         Helpers::boot();
     18▕
  ➜  19▕         Assets::define('slimscroll', [
     20▕             'deps' => 'jquery',
     21▕             'js' => 'https://cdn.jsdelivr.net/npm/jquery-slimscroll@1.3.8/jquery.slimscroll.min.js',
     22▕         ]);
     23▕     }

      +7 vendor frames

**Comment by z-song** [comment]
更新laravel-admin 2.x到最新，建议重新安装beta版本

**Comment by Forex44** [comment]
> LaravelAdmin2 ➤ php artisan admin:import helpers
> 
>    Error
> 
>   Class 'Encore\Admin\Assets' not found
> 
>   at vendor/laravel-admin-ext/helpers/src/HelpersServiceProvider.php:19
>      15▕         $this->loadViewsFrom(__DIR__.'/../resources/views', 'laravel-admin-helpers');
>      16▕
>      17▕         Helpers::boot();
>      18▕
>   ➜  19▕         Assets::define('slimscroll', [
>      20▕             'deps' => 'jquery',
>      21▕             'js' => 'https://cdn.jsdelivr.net/npm/jquery-slimscroll@1.3.8/jquery.slimscroll.min.js',
>      22▕         ]);
>      23▕     }
> 
>       +7 vendor frames
