### ISSUE TITLE
routes problem

### ISSUE THREAD

**Issue by qcol** [laravel-admin-extensions/helpers#4]
Still Something is wrong with DOC
I just installed helpers, but in doc I read:

```
//  add following code to app/Admin/routes.php
Admin::registerHelpersRoutes();
```

but when put this route I have error:
Call to undefined method Encore\Admin\Admin::registerHelpersRoutes()

When delete this route, helpers works(!?)

**Comment by z-song** [comment]
It's for old version of laravel-admin,  updated now.
