### ISSUE TITLE
Update for Laravel 5.6

### ISSUE THREAD

**Issue by ghost** [laravel-admin-extensions/helpers#9]
Please update the composer.json to allow installation on Laravel 5.6

**Comment by sergbbb** [comment]
Please!

**Comment by Devil0023** [comment]
Please!

**Comment by introin** [comment]
Any tweak to get it working with 5.6?

**Comment by z-song** [comment]
Since laravel-admin only supports LTS version of laravel's, ie laravel 5.5, these extensions can only be installed under laravel 5.5
